apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-webserver-app
  labels:
    app: library-webserver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-webserver-app
  template:
    metadata:
      labels:
        app: library-webserver-app
    spec:
      volumes:
        - name: config-nginx-volume
          configMap:
            name: config-map-nginx
      containers:
      - name: library-webserver-image
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: config-nginx-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
